// Generated by CoffeeScript 2.3.1
(function() {
  var ACCORDION;

  ACCORDION = {
    el: '#testobject',
    template: "<div class=\"ts accordion\">\n    <button @click=\"test\" >dfs</button>\n    <template v-for=\"(item, index) in items\">\n        <div :key=\"'title-${index}'\" class=\"title\">\n            <i class=\"dropdown icon\"></i>\n            {{ item.title }}\n        </div>\n        <div :key=\"'content-${index}'\" class=\"content\">\n            {{ item.content }}\n        </div>\n    </template>\n</div>",
    methods: {
      test: () => {
        return alert('Yee');
      }
    },
    data: () => {
      return {
        items: [
          {
            title: "Yee",
            content: "Wow"
          }
        ]
      };
    }
  };

  new Vue(ACCORDION);

}).call(this);
