#=======================================================
# Translation Information
#=======================================================

Information:
    Language: 台灣正體
    LanguageCode: zh-tw
    Path: zh-tw
    Flag: taiwan
    Version: 4.1.0

#=======================================================
# Translation Contributors
#=======================================================

Contributors:
    - Name: Yami Odymel
      Website: https://twitter.com/YamiOdymel
    - Name: coin3x
      Website:
    - Name: Sea-n
      Website: https://www.sean.taipei/

#=======================================================
#
#
#=======================================================

UI:
    Paragraph:
        #=======================================================
        # Navbar
        #=======================================================

        Navbar_GettingStarted: 開始使用
        Navbar_Components: 元件樣式
        Navbar_Examples: 實際範例

        #=======================================================
        # Examples
        #=======================================================

        Example_DesignedForDesktop: 看過來
        Example_DesignedForDesktop_Description: 這些範例是以電腦版本為設計初衷，若以行動裝置檢視，其格局可能會變形或被裁切。

        #=======================================================
        # Index
        #=======================================================

        Index_Title: Tocas UI
        Index_Description: 以最快最直覺的方式，建構多樣的網站與漸進式網路應用程式介面。
        Index_GettingStarted: 開始使用
        Index_Examples: 檢視範例

        Index_ComingSoon: 即將登場
        Index_ComingSoon_Description: 透過 Tocas Templates 模板元件庫來快速拼湊出應用程式、購物商城和企業宣傳介面。

        Index_Donators: 本專案由以下贊助者提供

        # Spotlight A
        Index_Spotlight_A_Title: 沒有 jQuery 相依性。
        Index_Spotlight_A_Description: 除了耗費多餘的網路頻寬之外；對於現代網站而言，使用 jQuery 已經不再是所謂的絕佳首選。Tocas UI 能與所有前端框架友善地搭配。
        Index_Spotlight_B_Title: 不需要 npm 或 Webpack。
        Index_Spotlight_B_Description: 沒有任何繁雜的手續：像是透過 npm 安裝一堆套件、在 Webpack 裡設置一堆載入器。你只需要將我們提供的 HTML 樣式標籤複製到你的網頁，然後…搭啦！就這麼容易。
        Index_Spotlight_C_Title: 完善的文件說明。
        Index_Spotlight_C_Description: 就算沒有撰寫過 Bootstrap 或是 Bulma、Semantic UI、Material Design…你也能夠透過完整的說明理解整個介面系統、響應式設計如何運作。
        Index_Spotlight_D_Title: 設計恍如隔世。
        Index_Spotlight_D_Description: 現有的元件與樣式一應俱全，已經為你做好萬全的準備。

        # Showcases
        Index_Showcase_ImageCard_Section: 圖片卡片
        Index_Showcase_ImageCard_Title: 好吃的千層蛋糕！
        Index_Showcase_ImageCard_Content: 在 5 月之前於線上網路門市訂購，現在還特別加贈限量環保袋。
        Index_Showcase_Button_Section: 按鈕
        Index_Showcase_Button_A: 送出
        Index_Showcase_Button_B: 取消
        Index_Showcase_Button_C: 刪除
        Index_Showcase_Label_Section: 標籤
        Index_Showcase_Label_A: 飛鳥湊
        Index_Showcase_Label_B: 西園寺風莉
        Index_Showcase_Statistic_Section: 統計數據
        Index_Showcase_Statistic_A_Label: 本月拜訪次數
        Index_Showcase_Statistic_B_Label: 總會員數
        Index_Showcase_Navbar_Section: 導航列
        Index_Showcase_Navbar_A: 使用者
        Index_Showcase_Navbar_B: 首頁
        Index_Showcase_Navbar_C: 新聞
        Index_Showcase_Table_Section: 表格
        Index_Showcase_Table_Header_A: 名稱
        Index_Showcase_Table_Header_B: 英文名稱
        Index_Showcase_Table_A_Cell_A: 半音商業銀行
        Index_Showcase_Table_A_Cell_B: Flat Bank
        Index_Showcase_Table_B_Cell_A: 對空音商事有限公司
        Index_Showcase_Table_B_Cell_B: Sorae & Co., Ltd.
        Index_Showcase_Table_C_Cell_A: 卡莉絲伊繁星
        Index_Showcase_Table_C_Cell_B: Caris Events
        Index_Showcase_Table_Footer: 統計筆數：3
        Index_Showcase_Breadcrumb_Section: 導覽標記
        Index_Showcase_Breadcrumb_A: 電影
        Index_Showcase_Breadcrumb_B: 科幻與冒險
        Index_Showcase_Breadcrumb_C: 星際效應
        Index_Showcase_Placeholder_Section: 預置內容
        Index_Showcase_Flag_Section: 國旗
        Index_Showcase_Rating_Section: 評分
        Index_Showcase_Selection_Section: 項目切換
        Index_Showcase_Selection_A: 省電
        Index_Showcase_Selection_B: 平衡
        Index_Showcase_Selection_C: 高效能

        # Features
        Index_Feature_A_Title: 明暗主題與響應式設計
        Index_Feature_A_Description: 支援暗黑模式且有針對行動裝置所設計的介面密度樣式。
        Index_Feature_A_Action: 檢視相關資訊
        Index_Feature_B_Title: 鬆離耦合性
        Index_Feature_B_Description: Tocas UI 元件以原子化設計令其能夠相互組合使用。
        Index_Feature_B_Action: 檢視元件
        Index_Feature_C_Title: 臨機應變
        Index_Feature_C_Description: 想做電商平臺？沒問題。管理介面？沒問題。社群網站？沒問題。
        Index_Feature_C_Action: 檢視範例

        # Let's Go
        Index_LetsGo_Title: 準備好了嗎？
        Index_LetsGo_Description: 複製下列 HTML 標籤至你的網頁，然後盡情地大鬧一番。
        Index_LetsGo_Code: >
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocas/4.1.0/tocas.min.css">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tocas/4.1.0/tocas.min.js"></script>

        Index_LetsGo_Action: 開始使用

        #=======================================================
        # Footer
        #=======================================================

        Footer_ToTop: 回到頂部
        Footer_GettingStarted: 開始使用
        Footer_Components: 元件樣式
        Footer_Examples: 實際範例
        Footer_Paragraph: 由來自 <span class="ts-flag is-taiwan-flag is-small"></span> 台灣的 <a href="https://twitter.com/YamiOdymel" target="_blank">Yami Odymel</a> 所設計，當然還有<a href="https://github.com/teacat/tocas/graphs/contributors" target="_blank">貢獻者們</a>的愛心❤️。原始碼授權方式為 <a href="https://github.com/teacat/tocas/blob/master/LICENSE" target="_blank">MIT</a>，文件則為 <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.zh_TW" target="_blank">CC 0</a> 公眾領域。還請盡情地使用、分享或一同改進。Tocas UI 是<a href="https://caris.events" target="_blank">卡莉絲伊繁星</a>的設計語言，而卡莉絲伊繁星屬<a href="https://sorae.co" target="_blank">對空音商事</a>。
        Footer_Translators: 台灣正體語系協作者：%s
        Footer_Logo_Alt: 擁有 Tocas UI 的所屬組織商標

        #=======================================================
        # Article
        #=======================================================

        Article_Hamburger_Aria: 展開導覽選單按鈕
        Article_Image_Placeholder_Alt: 不重要預置圖片，僅作為範例用
        Article_Example_Title: 範例
        Article_Schemes_Title: 明暗色系
        Article_Schemes_User: 遵循使用者設定
        Article_Schemes_Light: 亮色
        Article_Schemes_Dark: 暗色
        Article_Scaling_Title: 縮放
        Article_Scaling_Standard: 標準
        Article_Scaling_Large: 放大
        Article_Scaling_Small: 縮小
        Article_Introduction: 概要
        Article_Flag_Alias: 別名
        Article_SourceCode: 原始碼
        Article_LookingFor_Title: 在尋找相似的元件嗎？
        Article_ToTop: 回到頂部

        #=======================================================
        # Other
        #=======================================================

        TranslatorSeperator: 、

    ComponentsCategories:
        Introduction: 初入上手
        Layout: 格局設計
        Form: 表單
        Paragraphy: 文字與段落
        Feedback: 視覺回饋
        Media: 多媒體與圖示
        Data: 資料顯示
        Navigation: 導覽
        Application: 應用程式
        Others: 其他

    Components:
        GettingStarted: 開始使用
        Colors: 主題色系
        Responsive: 響應式設計
        About: 關於
        Box: 箱型容器
        Center: 絕對置中
        Container: 界限容器
        Content: 內容區塊
        Control: 表單控制項
        Grid: 網格系統
        Space: 空白間隔
        Row: 水平排列
        Wrap: 間隔容器
        Button: 按鈕
        Checkbox: 核取方塊
        Fieldset: 欄位分組
        File: 檔案上傳
        Input: 輸入欄位
        Radio: 選項按鈕
        Select: 下拉式選擇
        Selection: 項目切換
        Switch: 指撥開關
        Divider: 分隔線
        Header: 標題
        Mask: 內容遮罩
        Quote: 引言
        Segment: 片段
        Text: 文字
        Gauge: 圓形量測計
        Loading: 讀取狀態
        Modal: 快顯視窗
        Notice: 提示訊息
        Placeholder: 預置內容
        Procedure: 步驟指示器
        Progress: 進度條
        Snackbar: 簡短通知
        Avatar: 大頭貼
        Flag: 國家旗幟
        Icon: 圖示
        Iconset: 圖示項目
        Image: 多媒體圖片
        Imageset: 圖片組合
        Accordion: 可折疊內容
        Badge: 計數徽章
        Checklist: 檢查清單
        Chip: 關聯標籤
        Close: 關閉按鈕
        Conversation: 交談會話
        List: 清單
        Meta: 中繼資料
        Rating: 評分
        Statistic: 統計數據
        Table: 表格
        Breadcrumb: 導覽標記
        Menu: 選單
        Pagination: 頁數導覽列
        Tab: 分頁籤
        AppDialog: 對話視窗
        AppLayout: 格局劃分
        AppModal: 模態視窗
        AppNavbar: 導航列
        AppSidebar: 側邊欄
        Comment: 留言
        Dropdown: 彈出式選單

Components:
    - Name: Introduction
      Items:
          - GettingStarted
          - Colors
          - Responsive
          #- About
    - Name: Layout
      Items:
          - Box
          - Center
          - Container
          - Content
          - Control
          - Grid
          - Space
          - Row
          - Wrap
    - Name: Form
      Items:
          - Button
          - Checkbox
          - Fieldset
          - File
          - Input
          - Radio
          - Select
          - Selection
          - Switch
    - Name: Paragraphy
      Items:
          - Divider
          - Header
          - Mask
          - Quote
          - Segment
          - Text
    - Name: Feedback
      Items:
          - Gauge
          - Loading
          - Modal
          - Notice
          - Placeholder
          - Procedure
          - Progress
          - Snackbar
    - Name: Media
      Items:
          - Avatar
          - Flag
          - Icon
          - Iconset
          - Image
          - Imageset
    - Name: Data
      Items:
          - Accordion
          - Badge
          - Checklist
          - Chip
          - Close
          - Conversation
          - List
          - Meta
          - Rating
          - Statistic
          - Table
    - Name: Navigation
      Items:
          - Breadcrumb
          - Dropdown
          - Menu
          - Pagination
          - Tab
    - Name: Application
      Items:
          - AppLayout
          - AppNavbar
          - AppSidebar
