// Generated by CoffeeScript 2.0.0-beta2
var TocasSidebar, ts;

ts = function(selector) {
  var module;
  if (typeof selector !== 'object') {
    ts.selector = selector;
    ts.nodes = document.querySelectorAll(selector);
    return ts.fn;
  }
  module = selector;
  return ts.fn[module.$name()] = function($arg = null, $arg2 = null, $arg3 = null) {
    var $init, $methods, $nodes, $options, $selector, value;
    $selector = ts.selector;
    $nodes = ts.nodes;
    $init = module.$init;
    $methods = module.$methods;
    $options = module.$options;
    value = ts.fn;
    $nodes.forEach(function($element) {
      if (typeof $arg === 'object') {
        return value = $init($element, Object.assign($options, $arg));
      } else if ($arg === null) {
        return value = $init($element, $options);
      } else if (typeof $arg === 'string') {
        return value = $methods[$arg]($element, $arg2, $arg3);
      }
    });
    if (value === ts.fn) {
      return ts.fn;
    } else {
      return value;
    }
  };
};

ts.nodes = '';

ts.selector = '';

ts.fn = {};

TocasSidebar = (function() {
  class TocasSidebar {
    $name() {
      return 'sidebar';
    }

    $data() {
      return {};
    }

    $options() {
      return {
        dimPage: false,
        exclusive: false,
        scrollLock: false,
        closable: true
      };
    }

    $init($element, $options) {}

  };

  TocasSidebar.prototype.$methods = {
    "show": function($element, $arg2, $arg3) {
      return ts.fn;
    },
    "hide": function($element, $arg2, $arg3) {
      return ts.fn;
    },
    "toggle": function($element, $arg2, $arg3) {
      return ts.fn;
    },
    "attach events": function($element, $arg2, $arg3) {
      return ts.fn;
    }
  };

  return TocasSidebar;

})();

ts(new TocasSidebar());
