#=======================================================
# 標頭
# Header
#=======================================================

Title: 中繼資料
Description: 用以標示某個主體的時間、作者或統計資料和附屬行為。

#=======================================================
# 設定
# Settings
#=======================================================

Type: Article
Relatives:
    - List

#=======================================================
# 基本樣式
# Definitions
#=======================================================

Example:
    Centered: true
    HTML: |
        <div class="[[ts-meta]]">
            <a class="item">使用者條約</a>
            <a class="item">隱私政策</a>
            <a class="item">聯繫我們</a>
        </div>

Definitions:
    - Title: 外觀
      Description:
      Sections:
          - Title: 次要的
            Anchor: Secondary
            Description: 使其文字顏色變得更不顯眼。
            HTML: |
                <div class="ts-meta [[is-secondary]]">
                    <a class="item">天野望</a>
                    <a class="item">火井向百合</a>
                    <a class="item">成海遙香</a>
                </div>

          - Title: 文字對齊
            Anchor: Aligns
            Description: 更改文字的對齊方式。
            Remove:
                - <div class="ts-space"></div>
            HTML: |
                <div class="ts-meta [[is-start-aligned]]">
                    <a class="item">置起始位置</a>
                    <a class="item">置起始位置</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta [[is-center-aligned]]">
                    <a class="item">我置中</a>
                    <a class="item">我置中</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta [[is-end-aligned]]">
                    <a class="item">置結束位置</a>
                    <a class="item">置結束位置</a>
                </div>

          - Title: 尺寸
            Anchor: Sizes
            Description: 更改中繼資料的大小。
            Remove:
                - <div class="ts-space"></div>
            HTML: |
                <div class="ts-meta [[is-small]]">
                    <a class="item">朝武芳乃</a>
                    <a class="item">常陸茉子</a>
                    <a class="item">ムラサメ</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta">
                    <a class="item">朝武芳乃</a>
                    <a class="item">常陸茉子</a>
                    <a class="item">ムラサメ</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta [[is-large]]">
                    <a class="item">朝武芳乃</a>
                    <a class="item">常陸茉子</a>
                    <a class="item">ムラサメ</a>
                </div>

    - Title: 組合應用
      Description:
      Sections:
          - Title: 標題與資料
            Anchor: Composition Header
            Description: 在部落格或是一些文章列表中，經常能看到其標題底下會有一個中繼資料的區塊。
            HTML: |
                <div class="{{ts-header}}">野心更大的虛擬 YouTuber 團體邁向偶像化，而距離感也與日俱增</div>
                <div class="[[ts-meta]] is-secondary">
                    <a class="item">Yami Odymel</a>
                    <a class="item">2020 年 02 月 14 日</a>
                </div>
                <div class="{{ts-divider}} is-section"></div>
                <div class="{{ts-header}}">圖像複用、反轉、鏡射：怎麼將遊戲壓縮在 40 KB 以下還同時保持關卡獨特性？</div>
                <div class="[[ts-meta]] is-secondary">
                    <a class="item">Yami Odymel</a>
                    <a class="item">2020 年 01 月 18 日</a>
                </div>
